---
notifications:
  slack:
    on_failure: always
    
matrix:
  fast_finish: true
  include:         

    - name: "yarn via chocolatey Python 3.8 on Windows"
      os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
        - pip install -r requirements.txt
        - python --version
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      script:
      - choco install nodejs-lts
      - choco install yarn
      after_success:
        - deactivate
